package com.quicksilver.getmydrivercard;

public class Constants {
    public static final String BASE_SERVER_URL = "http://192.168.43.103:8080";
    public static final String USER = "USER";
    public static final String ADMIN = "ADMIN";
    public static final String REASON = "REASON";
    public static final String NEW_CARD = "NEW_CARD";
    public static final String LOST_CARD = "LOST";
    public static final String STOLEN_CARD = "STOLEN";
    public static final String CHANGE_CARD = "CHANGE_CARD";
    public static final String MALFUNCTION_BROKEN_CARD = "MALFUNCTION/BROKEN";
    public static final String EXCHANGE_CARD = "EXCHANGE_CARD";
    public static final String RENEW_CARD = "RENEW_CARD";
    public static final String WITHDRAWN_CARD = "WITHDRAWN_CARD";
    public static final String MESSAGE = "Please choose a reason";
    public static final String USER_TEXT = "USER";
    public static final String APPLICATION_TEXT = "USER";
    public static final String INTENT_REASON = "REASON";
    public static final String DATE_OF_EXPIRE = "Date of expire";
    public static final String ADDRESS_CHANGE = "ADDRESS CHANGE";
    public static final String NAME_CHANGE = "NAME CHANGE";
    public static final String PHOTO_CHANGE = "PHOTO CHANGE";
    public static final String DRIVING_LICENSE_CHANGE = "DRIVING LICENSE CHANGE";
    public static final String APPLICATION = "APPLICATION";
    public static final String EMAIL_ERROR = "Invalid email";
    public static final String PASSWORD_ERROR = "Invalid password";
    public static final String IDENTITY_NUMBER_ERROR = "Invalid identity number";
    public static final String FIRST_NAME_ERROR = "Invalid first name";
    public static final String FATHERS_NAME_ERROR = "Invalid father's name";
    public static final String LAST_NAME_ERROR = "Invalid last name";
    public static final String PHONE_NUMBER_ERROR = "Invalid phone number";
    public static final String DISTRICT_ERROR = "Invalid district";
    public static final String CITY_ERROR = "Invalid city";
    public static final String ADDRESS_ERROR = "Invalid address";
    public static final String IDENTITY_CARD_NUMBER_ERROR = "Invalid identity card number";
    public static final String DRIVING_LICENSE_NUMBER_ERROR = "Invalid driving license number number";
    public static final String ISSUED_BY_ERROR = "Invalid issued by";
    public static final String DATE_ERROR = "Invalid date!";
    public static final String CATEGORIES_ERROR = "Invalid categories!";
    public static final String COUNTRY_ERROR = "Invalid country!";
    public static final String PLACE_ERROR = "Invalid place!";
    public static final String TACHOGRAPH_CARD_NUMBER_ERROR = "Invalid tachograph card number!";
    public static final String FIELDS_ERROR = "Please fill all fields!";
}
